### ISSUE TITLE
stdin is stuck if popen `alda repl`

### ISSUE THREAD

**Issue by UlyssesZh** [alda-lang/alda-client-java#43]
```c
#include <stdio.h>
FILE *fp;
char str[100];
int main(int argc, char **argv) {
    fp = popen("alda repl", "w");
    scanf("%s", str);
    pclose(fp);
    return 0;
}
```
I want to use popen to operate alda repl in [alda-rb](https://github.com/UlyssesZh/alda-rb), and I failed. Then I wrote the C codes above to test.

It behaves as expected if `alda repl` is changed into into other commands.

The codes involving repl in [alda-rb](https://github.com/UlyssesZh/alda-rb) can be found in [alda-rb/lib/alda-rb.rb](https://github.com/UlyssesZh/alda-rb/blob/master/lib/alda-rb.rb) line 78-188 ([commit 3344566...](https://github.com/UlyssesZh/alda-rb/commit/3344566dbdd7061e05a9f7edef3418d39a23cadf)).

**Comment by daveyarwood** [comment]
`alda repl` is the only command that reads from STDIN in a loop. I would guess that you're running into difficulty because both your program and `alda` are trying to read from STDIN at the same time?

Alda's REPL isn't doing much that's complicated. I would recommend bypassing it and making your own REPL (maybe using something like [pry](https://github.com/pry/pry)?) that talks to the Alda server in the same way. The Alda server can do anything the REPL can; the REPL is really just a convenient interactive layer that makes requests to the server under the hood.

I think the only tricky part is that the REPL keeps track of a string of "history" that is just a single string of all of the previous Alda code that was entered that parsed/played successfully, separated by newlines, and it sends along that history with every request. That's how the Alda REPL can "remember" what instrument is playing and its attribute values (volume, tempo, etc.) You can pass this to the server using the `-i / --history` or `-I / --history-file` options with `alda play`:

```
alda play \
  -i "" \
  -c "bassoon: (vol 50) (tempo 180) (key-sig [:b :flat :major])"

alda play \
  -i "bassoon: (vol 50) (tempo 180) (key-sig [:b :flat :major])" \
  -c "o3 b8 > c d e f e d c < b2"

alda play \
  -i "bassoon: (vol 50) (tempo 180) (key-sig [:b :flat :major]) o3 b8 > c d e f e d c < b2" \
  -c "< b1"
```

The above is more or less what `alda repl` does when you enter the following lines of input:

```
bassoon: (vol 50) (tempo 180) (key-sig [:b :flat :major])
o3 b8 > c d e f e d c < b2
< b1
```

You should actually insert newlines between the lines in the history string, it's just challenging to do that in Bash. It may be easier to append each successful line of input to a temporary file and use the `-I / --history-file` option instead.

**Comment by daveyarwood** [comment]
Closing this for now since it's been a while - feel free to open if you'd like to continue the conversation!
